server:
  port: 8082

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

#Set swagger api url
springdoc:
  api-docs:
    enabled: true
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
    instances:
      auth-breaker-1:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000

      auth-breaker-2:
        failure-rate-threshold: 20  #
        sliding-window-size: 5
        sliding-window-type: time_based
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30000
        event-consumer-buffer-size: 5
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.Exception

application:
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days

spring:
  application:
    name: shop-auth
  data:
    redis:
      host: 192.168.93.128
      password: 111111

